const values = {
  // global values
  'inherit': 'wariskan',
  'initial': 'awal',
  'revert': 'kembalikan',
  'revert-layer': 'kembalikan-lapisan',
  'unset': 'hapus-setelan',

  'all': 'semua',
  'auto': 'otomatis',
  'bold': 'tebal',
  'both': 'kedua-duanya',

  // intrinsic values
  'max-content': 'konten-maksimal',
  'min-content': 'konten-minimal',
  'fit-content': 'muat-konten',

  // display values
  'static': 'statis',
  'relative': 'relatif',
  'absolute': 'absolut',
  'fixed': 'tetap',
  'hidden': 'tersembunyi',
  'none': 'tidak-ada',

  // flex and grid
  'flex-start': 'fleks-awal',
  'flex-end': 'fleks-akhir',
  'space-between': 'jarak-antara',
  'space-around': 'jarak-sekitar',
  'space-evenly': 'jarak-merata', 
  'row': 'baris',
  'row-reverse': 'baris-terbalik', 
  'column': 'kolom',
  'column-reverse': 'kolom-terbalik',

  // direction
  'start': 'awalan',
  'end': 'akhiran',
  'center': 'tengah',
  'left': 'kiri',
  'right': 'kanan',
  'justify': 'ratakan',
  'match-parent': 'sesuaikan-orangtua',

  'italic': 'miring',
  'no-repeat': 'tidak-berulang',
  'repeat': 'ulangi',
  'repeat-x': 'ulangi-x',
  'repeat-y': 'ulangi-y',

  // generic styles
  'normal': 'normal',
  'bolder': 'lebih-tebal',
  'lighter': 'lebih-tipis',
  'scroll': 'gulir',

  // lists
  'disc': 'disk',
  'circle': 'lingkaran',
  'square': 'kotak',
  'cjk-decimal': 'desimal-cjk',
  'decimal': 'desimal',
  'decimal-leading-zero': 'desimal-dengan-nol',
  'ethiopic-numeric': 'numerik-ethiopia',
  'lower-roman': 'romawi-kecil',
  'upper-roman': 'romawi-besar',
  'lower-greek': 'yunani-kecil',
  'lower-latin': 'latin-kecil',
  'upper-latin': 'latin-besar',
  'armenian': 'armenia',
  'georgian': 'georgia',
  'hebrew': 'ibrani',
  'lower-alpha': 'alpha-kecil',
  'upper-alpha': 'alpha-besar',

  // animation values
  'infinite': 'selamanya',
  'forwards': 'maju',
  'backwards': 'mundur',
  'alternate': 'bergantian',
  'paused': 'dihentikan',
  'running': 'berjalan',

  // styles (borders, outline)
  'thin': 'tipis',
  'medium': 'sedang',
  'thick': 'paling-tebal',
  'solid': 'solid',
  'dashed': 'putus-putus',
  'dotted': 'titik-titik',
  'double': 'ganda',
  'groove': 'alur',
  'ridge': 'alur-terbalik',
  'inset': 'di-dalam',
  'outset': 'di-luar',

  // cursor
  'default': 'bawaan',
  'context-menu': 'menu-konteks',
  'help': 'bantuan',
  'pointer': 'penunjuk',
  'progress': 'kemajuan',
  'wait': 'tunggu',
  'cell': 'sel',
  'crosshair': 'garis-bidik',
  'text': 'teks',
  'vertical-text': 'teks-vertikal',
  'alias': 'alias',
  'copy': 'salin',
  'move': 'gerakkan',
  'no-drop': 'tidak-bisa-drop',
  'not-allowed': 'tidak-diizinkan',
  'all-scroll': 'gulir-semua',

  'col-resize': 'ubah-ukuran-kolom',
  'row-resize': 'ubah-ukuran-baris',
  'n-resize': 'ubah-ukuran-u',
  's-resize': 'ubah-ukuran-s',
  'e-resize': 'ubah-ukuran-t',
  'w-resize': 'ubah-ukuran-b',
  'ns-resize': 'ubah-ukuran-us',
  'ew-resize': 'ubah-ukuran-tb',
  'ne-resize': 'ubah-ukuran-tl',
  'nw-resize': 'ubah-ukuran-bl',
  'se-resize': 'ubah-ukuran-te',
  'sw-resize': 'ubah-ukuran-bd',

  // quotes
  'open-quote': 'petik-buka',
  'close-quote': 'petik-tutup',

  // color scheme
  'light': 'terang',
  'dark': 'gelap',
  'only': 'hanya',

  // isolation
  'isolate': 'isolasikan',

  // visibility
  'visible': 'terlihat',
  'collapse': 'runtuhkan',

  // will-change
  'scroll-position': 'posisi-gulir',
  'contents': 'konten',

  // Colors
  'aqua': 'akua',
  'aquamarine': 'akuamarin',
  'azure': 'biru-terang',
  'beige': 'krem',
  'bisque': 'biskuit',
  'black': 'hitam',
  'blanchedalmond': 'almond-pucat',
  'blue': 'biru',
  'blueviolet': 'biru-keunguan',
  'chocolate': 'coklat',
  'coral': 'koral',
  'cornflowerblue': 'biru-cornflower',
  'cornsilk': 'rambut-jagung',
  'crimson': 'merah-pekat',
  'cyan': 'sian',
  'darkblue': 'biru-tua',
  'darkcyan': 'sian-tua',
  'darkgoldenrod': 'goldenrot-tua',
  'darkgreen': 'hijau-tua',
  'darkgray': 'abu-abu-tua',
  'darkkhaki': 'khaki-tua',
  'darkmagenta': 'magenta-tua',
  'darkolivegreen': 'hijau-zaitun-tua',
  'darkorange': 'oranye-tua',
  'darkorchid': 'anggrek-tua',
  'darkred': 'merah-tua',
  'darksalmon': 'salmon-tua',
  'darkseagreen': 'hijau-laut-tua',
  'darkviolet': 'violet-tua',
  'deeppink': 'merah-jambu-pekat',
  'deepskyblue': 'biru-langit-tua',
  'dimgrey': 'abu-abu-redup',
  'firebrick': 'merah-bata',
  'forestgreen': 'hijau-hutan',
  'gray': 'abu-abu',
  'green': 'hijau',
  'greenyellow': 'hijau-kekuningan',
  'honeydew': 'embun-madu',
  'indianred': 'merah-india',
  'ivory': 'gading',
  'khaki': 'khaki',
  'lavender': 'lavender',
  'lawngreen': 'hijau-rumput',
  'lemonchiffon': 'sifon-lemon',
  'lightblue': 'biru-muda',
  'lightcoral': 'koral-muda',
  'lightcyan': 'sian-muda',
  'lightgray': 'abu-abu-muda',
  'lightgreen': 'hijau-muda',
  'lightpink': 'merah-jambu-muda',
  'lightsalmon': 'salmon-muda',
  'lightseagreen': 'hijau-laut-muda',
  'lightskyblue': 'biru-langit-muda',
  'lightyellow': 'kuning-muda',
  'lime': 'jeruk-nipis',
  'limegreen': 'hijau-limau',
  'linen': 'linen',
  'maroon': 'merah-marun',
  'navy': 'biru-dongker',
  'olivedrab': 'zaitun',
  'orange': 'oranye',
  'orangered': 'oranye-kemerahan',
  'orchid': 'anggrek',
  'palegoldenrod': 'goldenrot-pucat',
  'palegreen': 'hijau-pucat',
  'paleturquoise': 'pirus-pucat',
  'peachpuff': 'persik',
  'pink': 'merah-muda',
  'purple': 'ungu',
  'red': 'merah',
  'rosybrown': 'coklat-kemerahan',
  'saddlebrown': 'sadel-coklat',
  'salmon': 'salmon',
  'sandybrown': 'coklat-pasir',
  'seagreen': 'hijau-laut',
  'seashell': 'kerang-laut',
  'silver': 'perak',
  'snow': 'salju',
  'tomato': 'tomat',
  'turquoise': 'pirus',
  'violet': 'violet',
  'wheat': 'gandum',
  'white': 'putih',
  'whitesmoke': 'asap-putih',
  'yellow': 'kuning',
  'yellowgreen': 'kuning-kehijauan'
}

module.exports = Object.keys(values).map(key => ({ en: key, id: values[key] }))
