import { writeFileSync } from 'node:fs'
import functions from '../src/functions.ts'
import properties from '../src/properties.ts'
import values from '../src/values.ts'
import type { Translation } from '../src/properties.ts'

function table(list: Translation[], format = (word: string) => word) {
  const rows = [...list]
    .sort((a, b) => a.en.localeCompare(b.en))
    .map(({ en, id }) => `| \`${format(en)}\` | \`${format(id)}\` |`)
  return ['| CSS | Bahasa Indonesia |', '| --- | --- |', ...rows].join('\n')
}

const markdown = `# Dictionary

<!-- Generated by \`pnpm dictionary\` from the word lists in src/. Do not edit. -->

Words not listed here pass through unchanged, so you can mix Indonesian and English freely.
Add your own words with the plugin's \`properties\`, \`values\` and \`functions\` options.

## Properties (${properties.length})

${table(properties)}

## Values (${values.length})

${table(values)}

## Functions (${functions.length})

${table(functions, (name) => `${name}()`)}
`

writeFileSync(new URL('../DICTIONARY.md', import.meta.url), markdown)
