import { writeFileSync } from 'node:fs'
import functions from '../src/functions.ts'
import media from '../src/media.ts'
import properties from '../src/properties.ts'
import type { Translation } from '../src/properties.ts'
import { pseudoClasses, pseudoElements } from '../src/selectors.ts'
import values from '../src/values.ts'

function sorted(list: Translation[]) {
  return [...list].sort((a, b) => a.en.localeCompare(b.en))
}

function table(list: Translation[], format = (word: string) => word) {
  const rows = sorted(list).map(({ en, id }) => `| \`${format(en)}\` | \`${format(id)}\` |`)
  return ['| CSS | Bahasa Indonesia |', '| --- | --- |', ...rows].join('\n')
}

const markdown = `# Dictionary

<!-- Generated by \`pnpm dictionary\` from the word lists in src/. Do not edit. -->

Words not listed here pass through unchanged, so you can mix Indonesian and English freely.
Add your own words with the plugin's \`properties\`, \`values\`, \`functions\`, \`media\`
and \`selectors\` options.

## Properties (${properties.length})

${table(properties)}

## Values (${values.length})

${table(values)}

## Functions (${functions.length})

${table(functions, (name) => `${name}()`)}

## Media queries (${media.length})

Used in \`@media\`, \`@supports\`, \`@container\` and \`@custom-media\`, together with the
properties and values above (\`lebar-minimal\` → \`min-width\`).

${table(media)}

## Pseudo-classes (${pseudoClasses.length})

${table(pseudoClasses, (name) => `:${name}`)}

## Pseudo-elements (${pseudoElements.length})

${table(pseudoElements, (name) => `::${name}`)}
`

// VS Code CSS custom data: https://github.com/microsoft/vscode-custom-data
function entries(list: Translation[], prefix = '') {
  return sorted(list).map(({ en, id }) => ({
    name: prefix + id,
    description: `${prefix}${en}`
  }))
}

const customData = {
  version: 1.1,
  properties: entries(properties),
  pseudoClasses: entries(pseudoClasses, ':'),
  pseudoElements: entries(pseudoElements, '::')
}

writeFileSync(new URL('../DICTIONARY.md', import.meta.url), markdown)
writeFileSync(
  new URL('../css-data.json', import.meta.url),
  JSON.stringify(customData, null, 2) + '\n'
)
